export enum SignalementTypeEnum {
  LOCATION_TO_UPDATE = 'LOCATION_TO_UPDATE',
  LOCATION_TO_DELETE = 'LOCATION_TO_DELETE',
  LOCATION_TO_CREATE = 'LOCATION_TO_CREATE',
}

export enum SignalementStatusEnum {
  PENDING = 'PENDING',
  IGNORED = 'IGNORED',
  PROCESSED = 'PROCESSED',
  EXPIRED = 'EXPIRED',
}
